version: '3'
services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
  db:
    platform: linux/x86_64 # for M1 Mac
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306
volumes:
  db-store: